# Generated by Django 5.1.4 on 2025-01-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='', max_length=10),
        ),
    ]
