# Generated by Django 5.1.4 on 2025-01-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyecto', '0001_initial'),
        ('Tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100, unique=True)),
                ('Fecha_inicio', models.DateField(blank=True)),
                ('Fecha_fin', models.DateField(blank=True)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyecto.proyecto')),
                ('Tarea', models.ManyToManyField(to='Tarea.tarea')),
            ],
        ),
    ]
