# Generated by Django 5.1.4 on 2025-01-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0001_initial'),
        ('Tarea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='Tarea',
        ),
        migrations.AddField(
            model_name='sprint',
            name='Tarea',
            field=models.ManyToManyField(to='Tarea.tarea'),
        ),
    ]
