# Generated by Django 5.1.4 on 2025-01-25 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Cliente',
            field=models.ManyToManyField(related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
