# Generated by Django 5.1.4 on 2025-01-26 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100, unique=True)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En proceso'), ('F', 'Finaizado')], default='P', max_length=1)),
                ('Personal', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('Comentario', models.CharField(max_length=300)),
                ('Estado', models.BooleanField(default=True)),
                ('Personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tarea.tarea')),
            ],
        ),
    ]
